# Generated by Django 3.1.3 on 2020-11-25 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_newloan_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='newloan',
            name='apply_date',
            field=models.DateField(default=datetime.date(2020, 11, 25)),
        ),
    ]
